export const LINK_BARRANQUILLA_MEETUP = 'https://www.meetup.com/es/barranquillajs';
export const LINK_BARRANQUILLA_LINKEDIN = 'https://www.linkedin.com/company/89602992';
export const LINK_BARRANQUILLA_WHATSAPP = 'https://chat.whatsapp.com/Cgkiea91hbpH2kErkjrmxb';
export const LINK_BARRANQUILLA_TWITTER = 'https://twitter.com/baq_js';
export const LINK_BARRANQUILLA_INSTAGRAM = 'https://www.instagram.com/barranquilla.js/';
export const LINK_BARRANQUILLA_TIKTOK = 'https://www.tiktok.com/@barranquillajs';
export const LINK_BARRANQUILLA_TWITCH = 'https://www.twitch.tv/barranquillajs';
export const LINK_BARRANQUILLA_YOUTUBE = 'https://www.youtube.com/channel/UC5VPQwD2C6RlLbifNapzhJA';
export * from './speakers';
export * from './sponsors';
export * from './meetups';
export * from './staff';
