import { staffData } from './staff';
import juanMendozaPhoto from '../public/assets/people/JUAN-MENDOZA.jpeg';

export const speakerData = [
  {
    name: 'Nicolas Camacho Aguilar',
    image: undefined,
    page: 'https://nicolas-camacho.vercel.app/',
    github: 'https://github.com/nicolas-camacho',
    linkedin: 'https://www.linkedin.com/in/nicolas-camacho-aguilar/',
  },
  {
    name: 'Gabriel Coronado Salas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Víctor Barrios Álvarez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Sebastian Mendoza',
    image: juanMendozaPhoto,
    page: 'https://juansebastianm.github.io/portfolio/',
    github: 'https://github.com/JuanSebastianM',
    linkedin: 'https://www.linkedin.com/in/juan-sebastian-mendoza-perez/',
  },
  {
    name: 'Juan Pablo Calao',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Rafael Villareal',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },

  {
    name: 'Edgardo Rodríguez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'David Villanueva',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  ...staffData,
  {
    name: 'Juan Camilo Torres',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Lennin Suescun',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Miguel Carmona',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Richard Roncancio',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Alberto De la Hoz',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Andrés Rojas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Jose Trezza',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
];
