import { staffData } from './staff';

export const speakerData = [
  {
    name: 'Gabriel Coronado Salas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Víctor Barrios Álvarez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Sebastian Mendoza',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Pablo Calao',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Rafael Villareal',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },

  {
    name: 'Edgardo Rodríguez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'David Villanueva',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  ...staffData,
  {
    name: 'Juan Camilo Torres',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Lennin Suescun',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Miguel Carmona',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Richard Roncancio',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Alberto De la Hoz',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Andrés Rojas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Jose Trezza',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
];
