import jesusBossaSpeaker from '../../public/assets/speakers/JESUS-SPEAKER.jpeg';

export const speakerData = [
  {
    name: 'Luis Alfredo Porras',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Jesus David Bossa',
    image: jesusBossaSpeaker,
    page: 'https://jesusbossa.dev/',
    github: 'https://github.com/makinox',
    linkedin: 'https://www.linkedin.com/in/makinox/',
  },
  {
    name: 'Aldair Moreno Collazo',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Gabriel Coronado Salas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Víctor Barrios Álvarez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Jesus Hernandez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Sebastian Mendoza',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Pablo Calao',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Rafael Villareal',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Edgardo Rodríguez',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'David Villanueva',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Juan Camilo Torres',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Lennin Suescun',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Miguel Carmona',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Richard Roncancio',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Alberto De la Hoz',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Andrés Rojas',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
  {
    name: 'Jose Trezza',
    image: undefined,
    page: undefined,
    github: undefined,
    linkedin: undefined,
  },
];
